# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceApp', '0002_auto_20180426_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='insuranceApp.Product'),
        ),
    ]
