# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceApp', '0003_profile_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='product',
            name='hospital',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.IntegerField(default=True),
        ),
    ]
